### ISSUE TITLE
caption for images

### ISSUE THREAD

**Issue by sniarchos** [estamos/NTUA-ECE-Thesis-Template#1]
Good morning! I use your template for my thesis, excellent work! I wanted to ask if there is a way to add a caption to an image in general, and to the cover picture in particular (I am very new to latex). Thanks a lot in advance!

**Comment by estamos** [comment]
Good morning ,

To add a caption to an image you simply have to modify 
`\caption{My image caption}` as it is shown in [`appE.tex`](https://github.com/estamos/NTUA-ECE-Thesis-Template/blob/03fd43628929294ae3f94061f0de1e48bba63b22/back_matter/appE.tex#L7) .

About cover picture, there is not current any ability to add a caption but as an alternative you can delete or comment 
`\coverpageimage{0.8}{figures/rdf.png}` in [`main.tex`](https://github.com/estamos/NTUA-ECE-Thesis-Template/blob/7a5e3e86cd9752d90696219402e14c4e636993ad/main.tex#L237) and try to add an illustration as in [`appE.tex`](https://github.com/estamos/NTUA-ECE-Thesis-Template/blob/master/back_matter/appE.tex) . 
If you do this, consider to modify width factor according to your image size .

ES
