### ISSUE TITLE
Σελιδοποίηση λίστας απόδοσης ξενόγλωσσων όρων

### ISSUE THREAD

**Issue by ghost** [estamos/NTUA-ECE-Thesis-Template#3]
Καλησπέρα, παρατήρησα ότι αν η λίστα απόδοσης ξενόγλωσσων όρων ξεπεράσει τη μια σελίδα, τότε αριθμείται μόνο η πρώτη. Πώς μπορώ να αριθμήσω και τις υπόλοιπες;

**Comment by estamos** [comment]
> Καλησπέρα, παρατήρησα ότι αν η λίστα απόδοσης ξενόγλωσσων όρων ξεπεράσει τη μια σελίδα, τότε αριθμείται μόνο η πρώτη. Πώς μπορώ να αριθμήσω και τις υπόλοιπες;

Καλησπέρα @you-know-who-lab  , ευχαριστώ πολύ για το feedback.
Το πρόβλημα διορθώθηκε και πλέον υπάρχει αρίθμηση σε κάθε σελίδα της λίστας απόδοσης ξενόγλωσσων όρων ανεξαρτήτως του πλήθους αυτής. 

Στην περίπτωση που κάποιος θέλει να αριθμήσει μόνο την 1η σελίδα της λίστας απόδοσης ξενόγλωσσων όρων πρέπει να βγάλει από σχόλιο την εντολή `\cleardoublepage\pagestyle{empty}` στο [`ntua-thesis.cls`](https://github.com/estamos/NTUA-ECE-Thesis-Template/blob/master/ntua-thesis.cls#L1680).

απόδοσης ξενόγλωσσων όρων

**Comment by ghost** [comment]
Ευχαριστώ πολύ, καλή συνέχεια.
